#!/usr/bin/env python
# -*- coding:UTF-8 -*-
import socket
for c in range(1,255,1):
    ip = '10.31.151.'+ str(c)
    for port in range(22,23,1):
        sk = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sk.settimeout(0.01)
        print "scannin port: %d" % port
        try:
            sk.connect((ip,port))
            print 'Server %s port %d OK' % (ip,port)
            if port == 22:
                print "Try to connect " + str(ip)+":22"
                import os
                os.system("ssh root@" + ip)
        except Exception:
            print 'Server %s port %d is not connected!' % (ip,port)
    sk.close()
c = c + 1
